[package]
authors = ["The Rust Project Developers"]
description = "Big integer implementation for Rust"
documentation = "https://docs.rs/num-bigint"
homepage = "https://github.com/rust-num/num-bigint"
keywords = ["mathematics", "numerics", "bignum"]
categories = [ "algorithms", "data-structures", "science" ]
license = "MIT/Apache-2.0"
name = "num-bigint-dig"
repository = "https://github.com/dignifiedquier/num-bigint"
version = "0.2.1"
readme = "README.md"
build = "build.rs"

[package.metadata.docs.rs]
features = ["std", "serde", "rand", "prime"]

[[bench]]
name = "bigint"

[[bench]]
name = "factorial"

[[bench]]
name = "gcd"

[[bench]]
harness = false
name = "shootout-pidigits"

[[bench]]
name = "prime"
harness = false


[dependencies.smallvec]
version = "0.6.7"
default-features = false

[dependencies.num-integer]
version = "0.1.39"
default-features = false

[dependencies.num-traits]
# git = "https://github.com/stichtingorganism/num-traits" 
version = "0.2.4"
default-features = false

[dependencies.num-iter]
version = "0.1.37"
default-features = false


[dependencies.rand]
optional = true
version = "0.5"
default-features = false
features = ["std"]

[dependencies.serde]
optional = true
version = "1.0"
default-features = false
features = ["std"]

[dev-dependencies.serde_test]
version = "1.0"

[dependencies.lazy_static]
version = "1.2.0"

[dependencies.byteorder]
version = "1.2.7"

[dev-dependencies]
criterion = "0.2"
rand_chacha = "0.1"

[features]
default = ["std", "i128", "u64_digit"]
i128 = ["num-integer/i128", "num-traits/i128"]
std = ["num-integer/std", "num-traits/std", "smallvec/std"]
u64_digit = []
prime = ["rand"]